# Generated by Django 3.2.19 on 2023-05-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230504_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_start',
            field=models.IntegerField(null=True),
        ),
    ]
