# Generated by Django 3.2.19 on 2023-05-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230505_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='length',
            field=models.IntegerField(),
        ),
    ]
